DROP TABLE `RECIPE`;
CREATE TABLE `RECIPE` (
  `RECIPEID` int(11) NOT NULL AUTO_INCREMENT,
  `RECIPE_NAME` varchar(200) DEFAULT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `RECIPETYPE` varchar(200) DEFAULT NULL,
  `VISITOR_COUNT` int(11) DEFAULT NULL,
  `PROCESS` text,
  PRIMARY KEY (`RECIPEID`)
);

DROP TABLE `RECIPE_INGREDIENTS`;
CREATE TABLE `RECIPE_INGREDIENTS` (
  `INGREDIENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INGREDIENT_NAME` varchar(200) DEFAULT NULL,
  `UOM` varchar(200) DEFAULT NULL,
  `QUANTITY` varchar(200) DEFAULT NULL,
  `RECIPEID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INGREDIENT_ID`)
);

INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES (`1`, `Test1`, `T`, `2013-07-05 00:00:00`, `Admin`, `Indian`, `1`, `x`);
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES (`2`, `Test2`, `T`, `2013-07-05 00:00:00`, `Admin`, `Continental`, `1`, `x`);
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES (`3`, `Test3`, `T`, `2013-07-05 00:00:00`, `Admin`, `Chiese`, `1`, `x`);
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES (`5`, `Test5`, `T`, NULL, `Admin`, `Bengali`, `2`, `x`);

INSERT INTO `test`.`RECIPE_INGREDIENTS` (`1`, `Salt`, `bla bla`, `100gm`, `1`);
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`2`, `Sugar`, `323`, `200gm`, `1`);
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`3`, `Chicken`, `342`, `1kg`, `1`);
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`4`, `Mutton`, `4dfgdf`, `1kg`, `2`);
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`5`, `Veg`, `dff`, `300gm`, `3`);